package fujin

const (
	OP_START int = iota

	// Writer
	OP_PRODUCE
	OP_PRODUCE_H

	OP_TX_BEGIN
	OP_TX_COMMIT
	OP_TX_ROLLBACK

	// Reader
	OP_SUBSCRIBE
	OP_SUBSCRIBE_CORRELATION_ID_ARG
	OP_SUBSCRIBE_ERROR_CODE_ARG
	OP_SUBSCRIBE_ERROR_PAYLOAD_ARG
	OP_SUBSCRIBE_ERROR_PAYLOAD
	OP_SUBSCRIBE_SUB_ID_ARG

	OP_SUBSCRIBE_H

	OP_UNSUBSCRIBE
	OP_UNSUBSCRIBE_CORRELATION_ID_ARG
	OP_UNSUBSCRIBE_ERROR_CODE_ARG
	OP_UNSUBSCRIBE_ERROR_PAYLOAD_ARG
	OP_UNSUBSCRIBE_ERROR_PAYLOAD

	OP_MSG
	OP_MSG_ID_ARG
	OP_MSG_ID_PAYLOAD
	OP_MSG_ARG
	OP_MSG_PAYLOAD

	OP_MSG_H
	OP_MSG_H_HEADERS_COUNT_ARG
	OP_MSG_H_HEADER_LEN
	OP_MSG_H_HEADER_PAYLOAD

	OP_FETCH
	OP_FETCH_N_ARG
	OP_FETCH_CORRELATION_ID_ARG
	OP_FETCH_ERROR_CODE_ARG
	OP_FETCH_ERROR_PAYLOAD_ARG
	OP_FETCH_ERROR_PAYLOAD
	OP_FETCH_SUBSCRIPTION_ID_ARG
	OP_FETCH_MSG_ID_ARG
	OP_FETCH_MSG_ID_PAYLOAD
	OP_FETCH_MSG_ARG
	OP_FETCH_MSG_PAYLOAD

	OP_FETCH_H
	OP_FETCH_H_N_ARG
	OP_FETCH_H_CORRELATION_ID_ARG
	OP_FETCH_H_ERROR_CODE_ARG
	OP_FETCH_H_ERROR_PAYLOAD_ARG
	OP_FETCH_H_ERROR_PAYLOAD
	OP_FETCH_H_SUBSCRIPTION_ID_ARG
	OP_FETCH_H_HEADERS_COUNT_ARG
	OP_FETCH_H_HEADER_LEN
	OP_FETCH_H_HEADER_PAYLOAD
	OP_FETCH_H_MSG_ID_ARG
	OP_FETCH_H_MSG_ID_PAYLOAD
	OP_FETCH_H_MSG_ARG
	OP_FETCH_H_MSG_PAYLOAD

	OP_ACK
	OP_ACK_CORRELATION_ID_ARG
	OP_ACK_ERROR_CODE_ARG
	OP_ACK_ERROR_PAYLOAD_ARG
	OP_ACK_ERROR_PAYLOAD
	OP_ACK_MSG_BATCH_LEN_ARG
	OP_ACK_MSG_ID_ARG
	OP_ACK_MSG_ID_PAYLOAD
	OP_ACK_MSG_ERROR_CODE_ARG
	OP_ACK_MSG_ERROR_PAYLOAD_ARG
	OP_ACK_MSG_ERROR_PAYLOAD

	OP_NACK
	OP_NACK_CORRELATION_ID_ARG
	OP_NACK_ERROR_CODE_ARG
	OP_NACK_ERROR_PAYLOAD_ARG
	OP_NACK_ERROR_PAYLOAD
	OP_NACK_MSG_BATCH_LEN_ARG
	OP_NACK_MSG_ID_ARG
	OP_NACK_MSG_ID_PAYLOAD
	OP_NACK_MSG_ERROR_CODE_ARG
	OP_NACK_MSG_ERROR_PAYLOAD_ARG
	OP_NACK_MSG_ERROR_PAYLOAD

	// Common
	OP_CORRELATION_ID_ARG
	OP_ERROR_CODE_ARG
	OP_ERROR_PAYLOAD_ARG
	OP_ERROR_PAYLOAD

	OP_DISCONNECT
)

type parseState struct {
	state      int
	argBuf     []byte
	metaBuf    []byte
	payloadBuf []byte

	ea errArg
	ma msgArg
	fa fetchArg
	aa ackArg
	ca correlationIDArg
}

type correlationIDArg struct {
	cID       []byte
	cIDUint32 uint32
}

type msgArg struct {
	sub   *Subscription
	idLen uint32
	len   uint32

	// For HMSG
	headers     map[string]string
	headerCount uint16
	headerStep  int
	headerLen   uint32
	headerBuf   []byte
	headerKey   string
}

type fetchArg struct {
	autoCommit bool
	subID      byte
	n          uint32
	handled    uint32
	msgs       []Msg
	err        chan error

	headers     map[string]string
	headerCount uint16
	headerStep  int
	headerLen   uint32
	headerBuf   []byte
	headerKey   string
}

type ackArg struct {
	n            uint32
	currMsgIDLen uint32
	resps        []AckMsgResponse
}

type errArg struct {
	errLen uint32
}
